/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('post').del()
  await knex('post').insert([
    {user_id: 1, title: 'Bacon ipsum', creation_date: "Fri May 06 2022 14:34:50 GMT-0600", content: "Bacon ipsum dolor amet pork picanha flank ground round. Venison landjaeger pork belly ribeye prosciutto. Flank jerky picanha, meatloaf cupim bresaola filet mignon meatball alcatra. Rump meatloaf meatball pork loin. Corned beef swine cow, brisket bacon boudin kevin kielbasa t-bone beef ribs chuck andouille prosciutto frankfurter. Burgdoggen short ribs filet mignon pancetta, spare ribs biltong salami porchetta kevin flank ribeye buffalo capicola."},
    {user_id: 2, title: 'Lorem ipsum', creation_date: "Fri May 06 2022 14:34:57 GMT-0600", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Amet venenatis urna cursus eget. Volutpat diam ut venenatis tellus in metus. Vel orci porta non pulvinar neque. A cras semper auctor neque vitae tempus quam pellentesque. Arcu risus quis varius quam quisque id. Gravida in fermentum et sollicitudin ac orci. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Non quam lacus suspendisse faucibus interdum. Consectetur adipiscing elit pellentesque habitant. Ac turpis egestas sed tempus urna et. Risus ultricies tristique nulla aliquet enim tortor at auctor."},
    {user_id: 1, title: 'Bacon ipsum Part 2', creation_date: "Fri May 06 2022 14:35:01 GMT-0600", content: "Venison leberkas meatball pork belly ribeye sirloin ground round hamburger landjaeger jowl biltong. Flank shoulder ham hock, chuck sausage porchetta shank salami. Jowl jerky tri-tip alcatra porchetta. Buffalo ham hock short loin cow brisket. Fatback burgdoggen short ribs pastrami. Shank doner strip steak capicola chuck pastrami biltong. Tongue ham hock turducken hamburger capicola, swine ground round shank tenderloin meatball ball tip ribeye."},
    {user_id: 2, title: 'Lorem ipsum Part 2', creation_date: "Fri May 06 2022 14:35:04 GMT-0600", content: "Faucibus in ornare quam viverra orci sagittis eu. Placerat in egestas erat imperdiet sed euismod nisi porta. A diam sollicitudin tempor id eu nisl nunc. Ut ornare lectus sit amet est placerat in. Mattis molestie a iaculis at erat. Magna fermentum iaculis eu non diam phasellus vestibulum. Morbi tristique senectus et netus et malesuada fames. Quam id leo in vitae turpis massa sed elementum. Nunc sed blandit libero volutpat sed. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Enim blandit volutpat maecenas volutpat blandit aliquam. Porta lorem mollis aliquam ut porttitor leo. Aenean euismod elementum nisi quis eleifend quam."},
    {user_id: 1, title: 'Bacon ipsum Part 3', creation_date: "Fri May 06 2022 14:35:11 GMT-0600", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Amet venenatis urna cursus eget. Volutpat diam ut venenatis tellus in metus. Vel orci porta non pulvinar neque. A cras semper auctor neque vitae tempus quam pellentesque. Arcu risus quis varius quam quisque id. Gravida in fermentum et sollicitudin ac orci. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Non quam lacus suspendisse faucibus interdum. Consectetur adipiscing elit pellentesque habitant. Ac turpis egestas sed tempus urna et. Risus ultricies tristique nulla aliquet enim tortor at auctor."},
    {user_id: 2, title: 'Lorem ipsum Part 3', creation_date: "Fri May 06 2022 14:35:23 GMT-0600", content: "Ribeye pork ham, meatball corned beef sirloin prosciutto picanha pastrami burgdoggen landjaeger tenderloin short loin drumstick. Meatloaf turducken pancetta turkey. Pork chop frankfurter tri-tip capicola kielbasa. Tongue ball tip bresaola rump. Flank porchetta andouille jowl corned beef, swine capicola pork loin sausage rump leberkas. Chislic frankfurter short loin, capicola venison short ribs cow bresaola pork leberkas pig flank salami pork chop. Shankle tail pork chop, andouille brisket chislic buffalo biltong flank pork doner ham picanha."}
  ]);
};
